#!/bin/bash
OCCLUM_CONF_ROOT_FS_MAC=$1
cat <<EOF
{
    "vm": {
        "user_space_size": "128MB"
    },
    "process": {
        "default_stack_size": "4MB",
        "default_heap_size": "8MB",
        "default_mmap_size": "16MB"
    },
    "mount": [
        {
            "target": "/",
            "type": "sefs",
            "source": ".occlum/build/mount/__ROOT",
            "options": {
                "integrity_only": true,
                "MAC": "$OCCLUM_CONF_ROOT_FS_MAC"
            }
        },
        {
            "target": "/root",
            "type": "sefs",
            "source": ".occlum/run/mount/root"
        },
        {
            "target": "/host",
            "type": "hostfs",
            "source": "."
        },
        {
            "target": "/tmp",
            "type": "ramfs"
        }
    ]
}
EOF
